### ISSUE TITLE
Command to load all kernel modules available for use

### ISSUE THREAD

**Issue by Wilglide** [jonasjacek/lpic-1-anki-flashcards#5]
The suggest answers modprobe -l or modprobe --list, do not exist.

This should be modprobe -a (tab, tab) to insert all module names on the command line.

Or even better lsmod to show the status of modules in the kernel.

**Comment by jonasjacek** [comment]
Hi @Wilglide,
you are right, `modprobe -l` or `modprobe --list` does not exist anymore. 
It is outdated. I've created the card on a Debian stable system, with a book from 2015. `man modprobe` used to state:

> -l --list
List all modules matching the given wildcard (or "*" if no wildcard is given). This option is provided for backwards compatibility and may go away in future: see find(1) and basename(1) for a more flexible alternative.

Source: https://forums.fedoraforum.org/showthread.php?283145-What-happened-to-quot-modprobe-l-quot

Right now I'm using Arch Linux due to some qt-update issues, which prevented me from using Anki and updating this repo. My current version is `kmod version 24 +XZ +ZLIB -EXPERIMENTAL`. The command `modprobe -l` does not exist anymore.

As the fedora forum and other sources suggest, we have to find expressions to find all loadable kernel modules. I will add some extra cards for this an remove the outdated card.

Your suggestion to use `lsmod` is unfortunately not an accurate alternative. It nicely formats the contents of the /proc/modules, showing what kernel modules are currently loaded. `modprobe -l` used to list all available modules, even the unloaded.

Thank you for taking the time to report this issue! 
I highly appreaciate this.
