### ISSUE TITLE
Incorrect answer

### ISSUE THREAD

**Issue by davidlott2024** [jonasjacek/lpic-1-anki-flashcards#7]
Question:
Command to read kernel messages in system log with less?

Answer:
<incorrect> $ sudo grep "kernel" /var/log/messages | less

This command syntax is incorrect.  The grep uses the proceeding command as input.  As structured, it would use the sudo command as input.  What is needed is to list the file and then send the contents to grep.  This command was tested via terminal command line and failed.

<correct> $ sudo less /var/log/syslog | grep "kernel"
This syntax uses root priviledges (sudo) to call the command (less) that lists the contents of the file (/var/log/syslog) and sends the output to grep that filters on the word "kernel" and then sends to stdout.  It should be noted that a better syntax would be to replace "less" with "cat" as it will process the whole file at once.  This was also tested via command line and worked.

Secondly, in Ubuntu (tested using Linux Mint 18), the system messages are sent to /var/log/syslog/  and kernel messages to /var/log/kern.log.  /var/log/messages instead aims at storing valuable, non-debug and non-critical messages. This log should be considered the "general system activity" log.

**Comment by jonasjacek** [comment]
Hi @davidlott2024,
thank you for taking the time to point out that error. 
I have generalized the question and researched 7 more questions, containing /var/log/messages. There are some things to fix for me. This issue is closed. For the other 7 questions, I will open a new one. 
Again, thank you for your help! I appreciate it a lot.
